const SET_NAME_VALUE = 'SET_NAME_VALUE';
const ADD_NAME_VALUE = 'ADD_NAME_VALUE';

const ADD_NEW_BANK = 'ADD_NEW_BANK';
const SET_BANK_NAME = 'SET_BANK_NAME';
const SET_BANK_INTEREST = 'SET_BANK_INTEREST';
const SET_BANK_AMOUNT = 'SET_BANK_AMOUNT';

export {
    ADD_NAME_VALUE,
    SET_NAME_VALUE,
    ADD_NEW_BANK,
    SET_BANK_NAME,
    SET_BANK_INTEREST,
    SET_BANK_AMOUNT,
};
